# Generated by Django 3.2.3 on 2021-06-02 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
