# Generated by Django 3.2.3 on 2021-06-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='userId',
        ),
        migrations.AddField(
            model_name='note',
            name='uname',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
